# Example configuration for space-cli
# This is a demo configuration for testing setup functionality

projects:
  example:
    name: 'Example Project' 
    repo: 'https://github.com/user/example-repo.git'
    sample_repo: 'https://github.com/user/example-samples.git'
    env_file: 'example.env.local'

global:
  src_dir: '~/src'
  workspace_base: 'workspaces'
  env_files_dir: './env-files'

templates:
  dir: './src/templates'

workflows:
  branch_patterns:
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
    - 'explore/**'
