# Example configuration for space-cli
# This is a demo configuration for testing setup functionality

projects:
  example:
    name: 'Example Project' 
    repo: 'https://github.com/user/example-repo.git'
    sample_repo: 'https://github.com/user/example-samples.git'
    env_file: 'example.env.local'
  
  next:
    name: 'Next.js Auth0 Project'
    repo: 'https://github.com/auth0/nextjs-auth0.git'
    sample_repo: 'https://github.com/auth0-samples/auth0-nextjs-samples.git'
    env_file: 'next.env.local'
    post-init: 'cd nextjs-auth0 && pnpm i && cd ../auth0-nextjs-samples/Sample-01 && pnpm i'

global:
  src_dir: '~/src'
  workspace_base: 'workspaces'
  env_files_dir: './env-files'

templates:
  dir: './src/templates'

workflows:
  branch_patterns:
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
    - 'explore/**'
